#!/bin/tcsh -f

set design="`basename $cwd`"

iverilog -o ./1_tb/output ./1_tb/${design}_tb.v ./0_design/$design.v && vvp ./1_tb/output
if (-e ./2_sim/$design.vcd) then
gtkwave ./2_sim/$design.vcd &
endif
exit
